FhenixProtocol/fheos

Makefile
gen.go
precompiles/contracts.go
solgen/common.ts
solgen/contracts_parser.ts
solgen/package-lock.json
solgen/package.json
solgen/solgen.ts
solgen/templates.ts
solgen/tsconfig.json
solidity/FHE.sol
solidity/FheOS.sol

https://fhenix.monday.com/boards/1216577959/views/4451803/pulses/1256521827
Now we can generate the solidity lib directly from fheos - it's still a bit rough around the edges, but a good starting point

Added solidity code generation directly from fheos

---

precompiles/contracts.go
precompiles/utils.go

Set a RWMutex on ctHashMap access

---

precompiles/contracts.go

for proper node-level error handling
1345355657

Change all errors returning from precompiles to ExecutionReverted

---

solgen/templates.ts
solidity/FHE.sol

Also modified external functions to be public

Added docstring to FHE library

---

precompiles/contracts.go

Decrypts in txs

---

.github/workflows/Test.yml
Dockerfile

go-tfhe (main PR): https://github.com/FhenixProtocol/go-tfhe/pull/36
nitro: https://github.com/FhenixProtocol/nitro/pull/64

Fix default logfile

---

solgen/common.ts
solgen/solgen.ts
solgen/templates.ts
solidity/FHE.sol
solidity/tests/contracts/And.sol
solidity/tests/contracts/Eq.sol
solidity/tests/contracts/Gt.sol
solidity/tests/contracts/Gte.sol
solidity/tests/contracts/Lt.sol
solidity/tests/contracts/Lte.sol
solidity/tests/contracts/Ne.sol
solidity/tests/contracts/Or.sol
solidity/tests/contracts/Xor.sol
solidity/tests/contracts/asEbool.sol
solidity/tests/contracts/asEuint16.sol
solidity/tests/contracts/asEuint32.sol
solidity/tests/contracts/asEuint8.sol

nitro: https://github.com/FhenixProtocol/nitro/pull/76
monday: https://fhenix.monday.com/boards/1216577959/views/4451803/pulses/1371851547

Shorthand decrypt

---

.gitmodules

Change https remote-url of warp-drive to ssh remote

---

hooks/hooks.go

Add magic bytes to ciphertext hashesMark ct

---

precompiles/contracts.go
precompiles/gas.go
precompiles/types/types.go
precompiles/utils.go

* Change precompile names to be an enum
* Remove fheUintType from fheos (unnecessary)
* Added return address for simulations with decryption of encrypted address

* Update gas prices

---

nitro-overrides/precompiles/FheOps.go

monday: https://fhenix.monday.com/boards/1216577959/pulses/1509272057
Still need to test it, hence only draft pr

Add a cache for the NetworkPublicKey in FheOps and force GetNetworkPublicKey to utilize it

---

chains/arbitrum/config.go
deployment/run.sh
precompiles/contracts.go

https://github.com/FhenixProtocol/warp-drive/pull/23

set log level for fheos which will be different from nitro

---

hooks/hooks.go
solgen/solgen.ts
solidity/FHE.sol

Hello
I fixed some minor typos,
Hope it helps.
Br,
Tudor.

Docs improvements

---

hooks/hooks.go

Just a cherry pick from https://github.com/FhenixProtocol/fheos/pull/163

Removing fheos Crit logs to master

---

http/main.go
precompiles/contracts.go

Update CT with specific Endpoint

---

http/main.go

Expose /GetNetworkPublicKey

---

Dockerfile
http/main.go
precompiles/contracts.go
precompiles/operations.go
precompiles/utils.go
storage/multiStorage.go
storage/pebble/db.go

Delete place holder

---

.github/workflows/Test.yml
fheos.iml

PR for create2

---

hooks/hooks.go
solidity/tests/contracts/wERC20.sol
solidity/tests/uninit.test.ts
solidity/tests/utils.ts

chore: fix some typos

---

.github/CODEOWNERS
.gitignore
chains/arbitrum/gen.go
http/main.go
nitro-overrides/precompiles/FheOps.go
precompiles/contracts.go
precompiles/gas.go
precompiles/types/types.go

#[derive(Serialize, Clone)]
struct UpdateCtEntry {
utype: u8,
value: String,
#[serde(rename = "securityZone")]
security_zone: u8,
}
#[derive(Serialize)]
struct UpdateCtRequest {
cts: Vec<UpdateCtEntry>,
signature: String,
}

update updatect flow to support zkverifier

---

go.mod
http/main.go
precompiles/contracts.go
rpc/rpc.go

* Update warp-drive
* Use new fhe-engine to expose /GetCrs

Add GetCrs endpoint
